# netlify.toml — Angular 20 SSR on Netlify Edge
[build]
  command = "npm ci && npm run build"
  publish = "dist/pokemon-gallery/browser"

[build.environment]
  NODE_VERSION = "20"

# Optional: your Node-based Netlify Functions (not used for SSR)
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# ⚠️ DO NOT add SPA redirects here, they break SSR routing.

# Local dev via Netlify CLI (optional — netlify dev proxies Angular's dev server)
[dev]
  command = "ng serve --port=4200 --host=localhost"
  targetPort = 4200
  port = 8888

# Cache headers for assets (optional)
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Angular SSR plugin
[[plugins]]
  package = "@netlify/angular-runtime"
